version: '3.8'

services:
  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-word-api
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  mongo-data:
